[package]
name = "callback_derive"
version = "0.1.0"
authors = ["Bill Avery <wravery@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
syn = { version = "1.0.67", features = ["full"] }
